### ISSUE TITLE
Can it use in Altera DE2-115 with Cyclone IV?

### ISSUE THREAD

**Issue by kensam94** [ShiGGie/FPGA-OV7670-cam#1]
I am trying your coding in Altera DE2-115 with Cyclone IV. Is it compatible? I have change the pin assignment and assign the camera pin to GPIO on fpga. But i have a problem, Altera DE2-115 do not have clock 27, what can i do?

**Comment by ShoeShi** [comment]
Indeed it should, and with those specs you can go for higher resolution by messing with the code. I only used CLOCK_27 for the audio because I wanted to test the spare clock I had, so it is not required. If you are using Quartus, you can setup your own audio pll using the wizard. Or ignore the audio component altogether.

You can share clocks as long as you do it right. If you have any questions, I recommend searching for the OV7670 specification sheets as It is where I got my clock requirements from, as well as http://tinyvga.com/vga-timing for vga.

**Comment by kensam94** [comment]
Okay, thanks. I will try it out
